# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

task :safe_migrate do
  spawn("rake db:migrate && rake db:rollback && rake db:migrate")

  loop do
    sleep 1
  end
end
